tables:
  - name: customers
    source_schema: public
    source_table: customers
    primary_key: [id]
    incremental_column: updated_at
    mode: incremental

  - name: orders
    source_schema: public
    source_table: orders
    primary_key: [order_id]
    incremental_column: created_at
    mode: incremental
